name: Infra only pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

env:
  BICEP_FILE: infra/main.bicep
  PARAMS_FILE: infra/main.bicepparam

jobs:
  validate:
    name: What-If Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep
        run: |
          az bicep install
          az bicep version

      - name: What-If (preview)
        run: |
          az deployment group what-if \
            --resource-group "${{ secrets.RESOURCE_GROUP }}" \
            --template-file "$BICEP_FILE" \
            --parameters @"$PARAMS_FILE" \
            --output json

  deploy:
    name: Deploy infra
    runs-on: ubuntu-latest
    needs: validate
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep
        run: |
          az bicep install

      - name: Deploy Bicep
        run: |
          az deployment group create \
            --resource-group "${{ secrets.RESOURCE_GROUP }}" \
            --template-file "$BICEP_FILE" \
            --parameters @"$PARAMS_FILE" \
            --output json
